// File generated by FlutterFire CLI.
// Updated for FIH Bilingual Science main project integration.
// 
// IMPORTANT: Android and iOS credentials need to be obtained from the main
// account owner after registering the Safe Water Heroes app in the Firebase Console.
// See README.md for integration instructions.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web credentials from FIH Bilingual Science main project
  // These now match the existing web app used by fih-bilingual-science-main.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxVL6EL_aHonRwn4O3qiFu_mwRImVyxtE',
    appId: '1:721841305201:web:35862093e50d183550cdd0',
    messagingSenderId: '721841305201',
    projectId: 'fih-bilingual-science',
    authDomain: 'fih-bilingual-science.firebaseapp.com',
    storageBucket: 'fih-bilingual-science.firebasestorage.app',
    measurementId: 'G-8LMEQGJRQ4',
  );

  // Android credentials - TODO: Replace with actual values from Firebase Console
  // The main account owner needs to:
  // 1. Add Android app with package name: com.safewater.safe_water_heroes
  // 2. Download google-services.json and update this file
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'ANDROID_API_KEY_FROM_MAIN_ACCOUNT', // TODO: Get from main account
    appId: '1:721841305201:android:SAFE_WATER_HEROES_ANDROID_APP_ID', // TODO: Get from main account
    messagingSenderId: '721841305201',
    projectId: 'fih-bilingual-science',
    storageBucket: 'fih-bilingual-science.firebasestorage.app',
  );

  // iOS credentials - TODO: Replace with actual values from Firebase Console
  // The main account owner needs to:
  // 1. Add iOS app with bundle ID: com.safewater.safeWaterHeroes
  // 2. Download GoogleService-Info.plist and update this file
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'IOS_API_KEY_FROM_MAIN_ACCOUNT', // TODO: Get from main account
    appId: '1:721841305201:ios:SAFE_WATER_HEROES_IOS_APP_ID', // TODO: Get from main account
    messagingSenderId: '721841305201',
    projectId: 'fih-bilingual-science',
    storageBucket: 'fih-bilingual-science.firebasestorage.app',
    iosBundleId: 'com.safewater.safeWaterHeroes',
  );

  // macOS uses same credentials as iOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'IOS_API_KEY_FROM_MAIN_ACCOUNT', // TODO: Get from main account
    appId: '1:721841305201:ios:SAFE_WATER_HEROES_IOS_APP_ID', // TODO: Get from main account
    messagingSenderId: '721841305201',
    projectId: 'fih-bilingual-science',
    storageBucket: 'fih-bilingual-science.firebasestorage.app',
    iosBundleId: 'com.safewater.safeWaterHeroes',
  );

  // Windows uses web credentials
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxVL6EL_aHonRwn4O3qiFu_mwRImVyxtE',
    appId: '1:721841305201:web:SAFE_WATER_HEROES_WINDOWS_APP_ID', // TODO: Get from main account
    messagingSenderId: '721841305201',
    projectId: 'fih-bilingual-science',
    authDomain: 'fih-bilingual-science.firebaseapp.com',
    storageBucket: 'fih-bilingual-science.firebasestorage.app',
    measurementId: 'G-SAFE_WATER_WINDOWS_MEASUREMENT', // TODO: Get from main account
  );
}
